#!/usr/bin/python
from subprocess import Popen
import sys

filename = sys.argv[1]
while True:
    print("\nStarting " + filename)
    p = Popen("python " + filename, shell=True)
    p.wait()

# Taken from https://techtldr.com/how-to-restart-python-script-after-exception-and-run-it-forever/ 
